---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pilot-probe
  namespace: pilot-integration
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - pilot-integration
  selector:
    matchLabels:
      app.kubernetes.io/name: pilot-probe
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
